/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../components/AppLink/index.vue')['default']
    BigFileUpload: typeof import('./../components/Upload/BigFileUpload.vue')['default']
    CopyButton: typeof import('./../components/CopyButton/index.vue')['default']
    DatePicker: typeof import('./../components/DatePicker/index.vue')['default']
    DictSelect: typeof import('./../components/DictSelect/index.vue')['default']
    DictTag: typeof import('./../components/DictTag/index.vue')['default']
    ECharts: typeof import('./../components/ECharts/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    FileListViewer: typeof import('./../components/Upload/FileListViewer.vue')['default']
    GithubCorner: typeof import('./../components/GithubCorner/index.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    InputTag: typeof import('./../components/InputTag/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    MenuIcon: typeof import('./../components/MenuIcon/index.vue')['default']
    MultiFileUpload: typeof import('./../components/Upload/MultiFileUpload.vue')['default']
    NoticeDropdown: typeof import('./../components/NoticeDropdown/index.vue')['default']
    OperationColumn: typeof import('./../components/OperationColumn/index.vue')['default']
    PageContent: typeof import('./../components/CURD/PageContent.vue')['default']
    PageModal: typeof import('./../components/CURD/PageModal.vue')['default']
    PageSearch: typeof import('./../components/CURD/PageSearch.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleFileUpload: typeof import('./../components/Upload/SingleFileUpload.vue')['default']
    TableSelect: typeof import('./../components/TableSelect/index.vue')['default']
    TextScroll: typeof import('./../components/TextScroll/index.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch/index.vue')['default']
    WangEditor: typeof import('./../components/WangEditor/index.vue')['default']
  }
}
